[package]
name = "chaos-network"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["dylib"]  # Changed from cdylib to dylib

[dependencies]
libc = "0.2"
lazy_static = "1.4.0"
regex = "1.7"
openssl-sys = "0.9.105" 
